name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: 'true'

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          filter: blob:none
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -s lint
      - name: Check code format
        run: pnpm ng-dev format changed --check ${{ github.event.pull_request.base.sha }}
      - name: Check commit message
        run: pnpm ng-dev commit-message validate-range ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: pnpm -s build
      - name: Run tests
        run: pnpm -s test:specs
      - name: Run integration samples
        run: pnpm -s integration:samples
      - name: Run integration specs
        run: pnpm -s integration:specs
      - name: Run integration watch specs
        run: pnpm -s integration:watch:specs
      - name: Run integration consumers
        run: pnpm -s integration:consumers

  build-and-test-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          filter: blob:none
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -s build
      - name: Run tests
        run: pnpm -s test:specs
      - name: Run integration samples
        run: pnpm -s integration:samples
      - name: Run integration specs
        run: pnpm -s integration:specs
